# constants.py - all game constants
# Thomas Fritchman
import pygame, math
from pygame.locals import *

# Screen
FPS = 60
WINDOWWIDTH = 600
WINDOWHEIGHT = 600
CENTER = (WINDOWWIDTH/2, WINDOWHEIGHT/2)
FOREGROUND_RADIUS = WINDOWWIDTH/2 - WINDOWWIDTH/50
BOUNDARY_RADIUS = WINDOWWIDTH/2

# Control
MOUSE_SENSE = 300.0

# Paddle
PADDLE_RADIUS = 160
PADDLE_INNER_RADIUS = 250
PADDLE_SWING_RADIUS = 250
PADDLE_SURF_SIZE = 320
PADDLE_SURF_CENTER = 160
PADDLE_WIDTH = 100
PADDLE_HEIGHT = 10
PADDLE_HYP = math.sqrt(((PADDLE_WIDTH/2)*(PADDLE_WIDTH/2))+((PADDLE_HEIGHT/2)*(PADDLE_HEIGHT/2)))
PADDLE_HYP_ANGLE = math.atan2((PADDLE_WIDTH/2), (PADDLE_HEIGHT/2))
PADDLE_EDGE_ANGLE = math.atan2((PADDLE_WIDTH/2), PADDLE_SWING_RADIUS-(PADDLE_HEIGHT/2))

# Ball
BALL_RADIUS = 10
BALL_WIDTH = 2*BALL_RADIUS
BALL_HEIGHT = 2*BALL_RADIUS
BALL_SPEED = 2

# Tile
TILE_WIDTH = 25
TILE_HEIGHT = 25

# Color constants
BLACK = Color(0, 0, 0)
WHITE = Color(255, 255, 255)
RED = Color(255, 0, 0)
GREEN = Color(0, 255, 0)
BLUE = Color(0, 0, 255)
CYAN = Color(0, 255, 255)
YELLOW = Color(255, 255, 0)
VIOLET = Color(192, 0, 255)
ORANGE = Color(255, 128, 0)

# Misc.
X = 0
Y = 1
TWOPI = math.pi * 2
PI = math.pi
